remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: "GATES-Lab"
description: "Using AI to speed up atmospheric transport and greenhouse gas emissions inference. Based at the Atmospheric Chemistry Research Group at the University of Bristol"

minimal_mistakes_skin: "air"

atom_feed:
  hide: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/GATES-Lab/GATES_LPDM_emulator"

include:
  - _pages
